# Generated by Django 3.2 on 2022-02-04 21:56

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependenciasactual',
            name='tipoDoc',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='dependenciasTipo',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.dependenciastipo'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='serviciosSedes',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.serviciossedes'),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='departamentos',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='sitios.departamentos'),
        ),
        migrations.AddField(
            model_name='centros',
            name='ciudades',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='departamentos', chained_model_field='departamentos', on_delete=django.db.models.deletion.CASCADE, to='sitios.ciudades'),
        ),
        migrations.AddField(
            model_name='centros',
            name='departamentos',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.departamentos'),
        ),
    ]
