# Generated by Django 3.2 on 2022-02-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dependencias',
            constraint=models.UniqueConstraint(fields=('dependenciasTipo', 'serviciosSedes', 'numero'), name='Constraint_dependencias'),
        ),
    ]
