# Generated by Django 3.2 on 2022-02-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0003_dependencias_constraint_dependencias'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='serviciossedes',
            constraint=models.UniqueConstraint(fields=('sedesClinica', 'servicios'), name='Constraint_ServiciosSedes'),
        ),
    ]
