# Generated by Django 3.2 on 2022-02-05 15:42

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0005_auto_20220205_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencias',
            name='serviciosSedes',
        ),
        migrations.AlterField(
            model_name='dependencias',
            name='servicios',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='servicios', chained_model_field='servicios', on_delete=django.db.models.deletion.CASCADE, to='sitios.serviciossedes'),
        ),
    ]
